name: Publish Package to npmjs and jsr
on:
  push:
    tags:
      - '@lilian1315/create-element@*.*.*'
      - '@lilian1315/elements-writable-properties-types@*.*.*'
  workflow_dispatch: # Allows manual triggering of the workflow.

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read
      id-token: write # Required for OIDC
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          run-install: true
      - run: vp run check
      - run: vp run build:core
      - run: vpx jsr publish
      - run: vpx pnpm publish --filter @lilian1315/* --no-git-checks --access public
